version: '3.9'

services:

  app:
    build:
      context: backend
    container_name: fastapi_app
    stop_signal: SIGKILL
    ports:
      - "8000:8000"
    volumes:
      - ./static/:/static
      - ./backend/app:/backend/app
      - ./.env:/.env
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_db/:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  nginx:
    image: my_nginx
    container_name: reverse_proxy_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static/:/data/www/static
    restart: unless-stopped
