version: '3.9'

services:

  postgres:
    image: postgres
#    restart: always
#    command:
#      - "postgres"
#      - "-c"
#      - "config_file=/var/lib/postgresql/data/postgresql.conf"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - ./db/:/var/lib/postgresql/data
#      - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d admin"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  nginx:
    image: my_nginx
    container_name: reverse_proxy_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static/:/data/www/static
