"""init revision

Revision ID: aad4d07712a2
Revises:
Create Date: 2023-04-12 11:30:46.700167

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "aad4d07712a2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "table_media",
        sa.Column("media_id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("link", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("media_id"),
    )
    op.create_table(
        "table_users",
        sa.Column("user_id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("user_name", sa.String(length=20), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=True),
        sa.Column("last_name", sa.String(length=50), nullable=True),
        sa.Column("reg_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("user_name"),
    )
    op.create_table(
        "table_followers",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("follower_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["table_users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["table_users.user_id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "follower_id"),
    )
    op.create_table(
        "table_tweets",
        sa.Column("tweet_id", sa.Integer(), sa.Identity(always=True), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["table_users.user_id"],
        ),
        sa.PrimaryKeyConstraint("tweet_id"),
    )
    op.create_table(
        "table_likes",
        sa.Column("tweet_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tweet_id"],
            ["table_tweets.tweet_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["table_users.user_id"],
        ),
        sa.PrimaryKeyConstraint("tweet_id", "user_id"),
    )
    op.create_table(
        "table_media_tweet_relation",
        sa.Column("tweet_id", sa.Integer(), nullable=False),
        sa.Column("media_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["media_id"], ["table_media.media_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tweet_id"],
            ["table_tweets.tweet_id"],
        ),
        sa.PrimaryKeyConstraint("tweet_id", "media_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("table_media_tweet_relation")
    op.drop_table("table_likes")
    op.drop_table("table_tweets")
    op.drop_table("table_followers")
    op.drop_table("table_users")
    op.drop_table("table_media")
    # ### end Alembic commands ###
